### ISSUE TITLE
Installtion is not working

### ISSUE THREAD

**Issue by alessandromorra** [lgulich/lg-linter#2]
**Describe the bug**
Some errors are generated when installing the linter, I am not sure if the errors are critical though. However, when I try to initialize the linter in my repo I get the following error:
```
✔ ~/compp_ws/src/compp_core [feature/add_mynt_eye_d|✚ 1…1] 
11:48 $ init_lg_linter
init_lg_linter: command not found

```

**Expected behavior**
I do no expect errors to appear when downloading and initializing.

**To Reproduce**
Install the linter as suggested and then initialized it in my repo:
```
sudo apt update
sudo apt install -y clang-format shellcheck
pip3 install lg-linter
init_lg_linter
```

**Additional context**
My console output: 
```
alessandromorra@alessandromorra-ThinkPad-P51:~/compp_ws/src$ pip3 install lg-linter
Collecting lg-linter
  Downloading https://files.pythonhosted.org/packages/38/27/5ec2061f1cc3798289d7b69ec62fef334ba1317baca8c350799c0ec87347/lg-linter-0.1.9.tar.gz
Collecting gitpython (from lg-linter)
  Downloading https://files.pythonhosted.org/packages/19/1a/0df85d2bddbca33665d2148173d3281b290ac054b5f50163ea735740ac7b/GitPython-3.1.1-py3-none-any.whl (450kB)
    100% |████████████████████████████████| 460kB 1.6MB/s 
Collecting lg-cpplint (from lg-linter)
  Downloading https://files.pythonhosted.org/packages/53/12/17bd21e9e34188f0b6b6d48a5994cfe59608bdddd3df128dbfd358365499/lg-cpplint-0.1.1.tar.gz (331kB)
    100% |████████████████████████████████| 337kB 2.8MB/s 
Collecting pylint (from lg-linter)
  Downloading https://files.pythonhosted.org/packages/64/9a/1c975d26b6148eb8dba4e50127382e37f9dfc2b18dafeb07e230901cbd38/pylint-2.5.0-py3-none-any.whl (324kB)
    100% |████████████████████████████████| 327kB 2.5MB/s 
Collecting yapf (from lg-linter)
  Downloading https://files.pythonhosted.org/packages/c1/5d/d84677fe852bc5e091739acda444a9b6700ffc6b11a21b00dd244c8caef0/yapf-0.30.0-py2.py3-none-any.whl (190kB)
    100% |████████████████████████████████| 194kB 6.2MB/s 
Collecting gitdb<5,>=4.0.1 (from gitpython->lg-linter)
  Downloading https://files.pythonhosted.org/packages/74/52/ca35448b56c53a079d3ffe18b1978c6e424f6d4df02404877094c89f5bfb/gitdb-4.0.4-py3-none-any.whl (63kB)
    100% |████████████████████████████████| 71kB 11.1MB/s 
Collecting astroid<=2.5,>=2.4.0 (from pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/7c/f6/880bade8329525fd9aa9051891b4b8fe2e52c7aab7412443f8743028a590/astroid-2.4.0-py3-none-any.whl (327kB)
    100% |████████████████████████████████| 327kB 4.5MB/s 
Collecting isort<5,>=4.2.5 (from pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/e5/b0/c121fd1fa3419ea9bfd55c7f9c4fedfec5143208d8c7ad3ce3db6c623c21/isort-4.3.21-py2.py3-none-any.whl (42kB)
    100% |████████████████████████████████| 51kB 13.0MB/s 
Collecting toml>=0.7.1 (from pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/a2/12/ced7105d2de62fa7c8fb5fce92cc4ce66b57c95fb875e9318dba7f8c5db0/toml-0.10.0-py2.py3-none-any.whl
Collecting mccabe<0.7,>=0.6 (from pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/87/89/479dc97e18549e21354893e4ee4ef36db1d237534982482c3681ee6e7b57/mccabe-0.6.1-py2.py3-none-any.whl
Collecting smmap<4,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython->lg-linter)
  Downloading https://files.pythonhosted.org/packages/27/b1/e379cfb7c07bbf8faee29c4a1a2469dbea525f047c2b454c4afdefa20a30/smmap-3.0.2-py2.py3-none-any.whl
Collecting typed-ast<1.5,>=1.4.0; implementation_name == "cpython" and python_version < "3.8" (from astroid<=2.5,>=2.4.0->pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/90/ed/5459080d95eb87a02fe860d447197be63b6e2b5e9ff73c2b0a85622994f4/typed_ast-1.4.1-cp36-cp36m-manylinux1_x86_64.whl (737kB)
    100% |████████████████████████████████| 747kB 1.5MB/s 
Collecting lazy-object-proxy==1.4.* (from astroid<=2.5,>=2.4.0->pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/0b/dd/b1e3407e9e6913cf178e506cd0dee818e58694d9a5cd1984e3f6a8b9a10f/lazy_object_proxy-1.4.3-cp36-cp36m-manylinux1_x86_64.whl (55kB)
    100% |████████████████████████████████| 61kB 11.2MB/s 
Collecting wrapt~=1.11 (from astroid<=2.5,>=2.4.0->pylint->lg-linter)
  Downloading https://files.pythonhosted.org/packages/82/f7/e43cefbe88c5fd371f4cf0cf5eb3feccd07515af9fd6cf7dbf1d1793a797/wrapt-1.12.1.tar.gz
Collecting six~=1.12 (from astroid<=2.5,>=2.4.0->pylint->lg-linter)
  Using cached https://files.pythonhosted.org/packages/65/eb/1f97cb97bfc2390a276969c6fae16075da282f5058082d4cb10c6c5c1dba/six-1.14.0-py2.py3-none-any.whl
Building wheels for collected packages: lg-linter, lg-cpplint, wrapt
  Running setup.py bdist_wheel for lg-linter ... done
  Stored in directory: /home/alessandromorra/.cache/pip/wheels/00/08/f0/9fa48639664031e9d451e6075943ff0ae74e8eb8d611380aea
  Running setup.py bdist_wheel for lg-cpplint ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-92wh_t0_/lg-cpplint/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpps6tq_nbpip-wheel- --python-tag cp36:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib
  copying cpplint.py -> build/lib
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  copying build/lib/cpplint.py -> build/bdist.linux-x86_64/wheel
  running install_egg_info
  running egg_info
  writing lg_cpplint.egg-info/PKG-INFO
  writing dependency_links to lg_cpplint.egg-info/dependency_links.txt
  writing entry points to lg_cpplint.egg-info/entry_points.txt
  writing requirements to lg_cpplint.egg-info/requires.txt
  writing top-level names to lg_cpplint.egg-info/top_level.txt
  reading manifest file 'lg_cpplint.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '.tox' found anywhere in distribution
  warning: no previously-included files matching '*~' found anywhere in distribution
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '.coverage' found anywhere in distribution
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  warning: no previously-included files matching '*.db' found anywhere in distribution
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.orig' found anywhere in distribution
  writing manifest file 'lg_cpplint.egg-info/SOURCES.txt'
  Copying lg_cpplint.egg-info to build/bdist.linux-x86_64/wheel/lg_cpplint-0.1.1.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-92wh_t0_/lg-cpplint/setup.py", line 82, in <module>
      'lint': Lint
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 257, in run
      self.distinfo_dir)
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 427, in egg2dist
      distribution=self.distribution)
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 177, in pkginfo_to_dict
      new_requirements = sorted(convert_requirements(requirements))
    File "/usr/lib/python3/dist-packages/wheel/metadata.py", line 234, in convert_requirements
      parsed_requirement = pkg_resources.Requirement.parse(req)
    File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2988, in parse
      req, = parse_requirements(s)
  ValueError: not enough values to unpack (expected 1, got 0)
  
  ----------------------------------------
  Failed building wheel for lg-cpplint
  Running setup.py clean for lg-cpplint
  Running setup.py bdist_wheel for wrapt ... done
  Stored in directory: /home/alessandromorra/.cache/pip/wheels/b1/c2/ed/d62208260edbd3fa7156545c00ef966f45f2063d0a84f8208a
Successfully built lg-linter wrapt
Failed to build lg-cpplint
Installing collected packages: smmap, gitdb, gitpython, lg-cpplint, typed-ast, lazy-object-proxy, wrapt, six, astroid, isort, toml, mccabe, pylint, yapf, lg-linter
  Running setup.py install for lg-cpplint ... done
Successfully installed astroid-2.4.0 gitdb-4.0.4 gitpython-3.1.1 isort-4.3.21 lazy-object-proxy-1.4.3 lg-cpplint-0.1.1 lg-linter-0.1.9 mccabe-0.6.1 pylint-2.5.0 six-1.14.0 smmap-3.0.2 toml-0.10.0 typed-ast-1.4.1 wrapt-1.12.1 yapf-0.30.0

```

and then in my repo: 

```
✔ ~/compp_ws/src/compp_core [feature/add_mynt_eye_d|✚ 1…1] 
11:48 $ init_lg_linter
init_lg_linter: command not found
✘-127 ~/compp_ws/src/compp_core [feature/add_mynt_eye_d|✚ 1…1] 

```

**Comment by lgulich** [comment]
Hmm not exactly sure whats happening here. The `Failed building wheel for lg-cpplint` error is expected but should not make a difference. I have also just tried installing the linter on a fresh os and there it works fine.

Did you try this on a system which had an earlier version of lg-linter installed?
If so maybe `pip3 install lg-linter --upgrade` might be able to help

**Comment by alessandromorra** [comment]
`pip3 install lg-linter --upgrade` thanks this fixed it.
